version: '3.8'

services:
  bot:
    build: .
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - FACEPP_API_KEY=${FACEPP_API_KEY}
      - FACEPP_API_SECRET=${FACEPP_API_SECRET}
      - AILAB_API_KEY=${AILAB_API_KEY}
      - AILAB_API_SECRET=${AILAB_API_SECRET}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
      - YOOKASSA_SHOP_ID=${YOOKASSA_SHOP_ID}
      - YOOKASSA_SECRET_KEY=${YOOKASSA_SECRET_KEY}
      - WEBHOOK_URL=${WEBHOOK_URL}
      - PORT=8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  worker:
    build: .
    command: python worker.py
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_URL=${REDIS_URL}
      - FACEPP_API_KEY=${FACEPP_API_KEY}
      - FACEPP_API_SECRET=${FACEPP_API_SECRET}
      - AILAB_API_KEY=${AILAB_API_KEY}
      - AILAB_API_SECRET=${AILAB_API_SECRET}
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    depends_on:
      - postgres
      - redis
    restart: unless-stopped

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=hd_lookism
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data:
